# Python Arrays

In [ ]:
import numpy as np
from matplotlib import pyplot as plt

x = np.arange(0, 10)
y = x + 1

plt.title("Matplotlib demo")
plt.xlabel("x axis caption")
plt.ylabel("y axis caption")
plt.plot(x, y, linestyle='-', color='blue')
plt.show()


In [ ]:
# Python program to demonstrate
# Creation of Array
# importing "array" for array creations
import array as arr
# creating an array with integer type
a = arr.array('i', [1, 2, 3])
# printing original array
print ("The new created array is : ", end =" ")
for i in range (0, 3):
    print (a[i], end =" ")
print(a)
# creating an array with float type
b = arr.array('d', [2.5, 3.2, 3.3])

# printing original array
print ("The new created array is : ", end =" ")
for i in range (0, 3):
    print (b[i], end =" ")

The new created array is :  1 2 3 array('i', [1, 2, 3])
The new created array is :  2.5 3.2 3.3 

![image.png](attachment:image.png)

In [ ]:
# Python program to demonstrate
# Adding Elements to a Array

# importing "array" for array creations
import array as arr

a = arr.array('i',[1, 2, 3])

# inserting array using insert() function
a.insert(1,4)

print ("Array after insertion : ", end =" ")
for i in (a):
	print (i, end =" ")
print()

# array with float type
b = arr.array('d', [2.5, 3.2, 3.3])

# adding an element using append()
b.append(4.4)
print(b)

Array after insertion :  1 4 2 3 
array('d', [2.5, 3.2, 3.3, 4.4])


In [ ]:
# Python program to demonstrate
# Removal of elements in a Array
import array
arr = array.array('i', [1, 2, 3, 1, 5])

# using pop() to remove element at 2nd position
print ("The popped element is : ", end ="")
print (arr.pop(2))

# printing array after popping
print ("The array after popping is : ", end ="")
for i in range (0, 4):
	print (arr[i], end =" ")

print("\r")

# using remove() to remove 1st occurrence of 1
arr.remove(1)

# printing array after removing
print ("The array after removing is : ", end ="")
for i in range (0, 3):
	print (arr[i], end =" ")


The popped element is : 3
The array after popping is : 1 2 1 5 
The array after removing is : 2 1 5 

In [ ]:
# Python program to demonstrate silicing of elements in a Array

import array as arr
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

a = arr.array('i', l)
print("Intial Array: ")
for i in (a):
	print(i, end =" ")

# Print elements of a range
# using Slice operation
Sliced_array = a[3:8]
print("\nSlicing elements in a range 3-8: ")
print(Sliced_array)

# Print elements from a
# pre-defined point to end
Sliced_array = a[5:]
print("\nElements sliced from 5th element till the end: ")
print(Sliced_array)

# Printing elements from
# beginning till end
Sliced_array = a[:]
print("\nPrinting all elements using slice operation: ")
print(Sliced_array)
print("array a")
print(a)
# updating a element in a array
a[2] = 6
print("Array after updation : ", end ="")
for i in range(10):
    print (a[i], end =" ")
print()

# Difference between array and list
Array can store only one type of element, whereas lists can store different types of elements.


# Introduction To Numpy
1. Numpy is python package and it stands for numerical python
2. Fundamental packages for numerical computations in python
3. Supports N-dimensional array objects that can be used for processing multidimensional data
4. Supports diferrent data types

Array

1. An array is a data structure that stores values of same data type.


NumPy Array

1. A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers
2. The number of dimensions is the rank of array
3. The shape of an array is a tuple integers giving the size of the array along each dimension

In [ ]:
# To create Nmpy array, we first need to import the numpy package
import numpy as np
array=np.array([1,2,3,4,5,6])
#or
#array=np.array([1,2,3,4,5,6],int)
#or
#my_list =[1,2,3,4,5,6]
#array=np.array(my_list,dtype = int)
print(array)

[1 2 3 4 5 6]


In [ ]:
# basic array characteristics
array= np.array([[1,2,3],[1,4,3],[4,5,6]])
print(array)
print(type(array))
print(len(array[0]))
print(array.size)
print(array.ndim)
print(array.shape)
print(array.dtype)
row,col = array.shape
print(array.shape[0])

[[1 2 3]
 [1 4 3]
 [4 5 6]]
<class 'numpy.ndarray'>
3
9
2
(3, 3)
int64
3


In [ ]:
#Initializing numpy array from nested Python Lists
my_list2 = [1,2,3,4,5]
my_list3 = [2,3,4,5,6]
my_list4 = [9,7,6,8,9]
pri_arr = np.array([my_list2,my_list3,my_list4])
print(pri_arr)
print(pri_arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
(3, 5)


In [ ]:
#indexing in numpy array
import numpy as np
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
# Printing a range of Array with the use of slicing method
sliced_arr = arr[1::2] # [start:end:increment]
print ("Array with alternative rows and alternate columns(0 and 2):\n", sliced_arr)

In [ ]:
#create array using arange() function
#create array using ones() and zeros()
# Create a sequence of integers from 2 to 11 with steps of 2
x = np.arange(5)
print(x)
a= np.arange(2,12,2)
print(a)
# Creating a 2X2 array with all zeros
b= np.zeros(5)

print(b)
# Creating a 2X2 array with all ones
c= np.ones((2,2)) # default type is float
print(c)
# Create an array with random values
d = np.random.random((2,2))
print(d)
#Create a sequence of 10 values in range 0 to 5
e = np.linspace(0, 5, 10,True)
print(e)

[0 1 2 3 4]
[ 2  4  6  8 10]
[0. 0. 0. 0. 0.]
[[1. 1.]
 [1. 1.]]
[[0.17072591 0.05284663]
 [0.81155264 0.19374928]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
import numpy as np
#Reshape and Flatten array
array=np.array([1,2,3,4,5,6])
print(array)
array.shape=(3,2)
print("array after shape function: ",array)
array2=array.reshape(2,3)
print(array2)
print("Shape of array2: ",array2.shape)
flarr = array2.flatten()
print(flarr)
flarr1 = array2.flatten('F')
print(flarr1)

[1 2 3 4 5 6]
array after shape function:  [[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
Shape of array2:  (2, 3)
[1 2 3 4 5 6]
[1 4 2 5 3 6]


# Basic operations:
1. Operations on single array
2. Unary operators
3. Binary operators
4. Universal functions (ufunc)
5. Sorting array

In [ ]:
# basic operations on single array
import numpy as np
a = np.array([1, 2, 5, 3])
# add 1 to every element
print ("Adding 1 to every element:", a+1)
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
# square each element
print ("Squaring each element:", a**2)
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [ ]:
# Prompt the user to input a word
word = input("Input a word to reverse: ")

# Iterate through the characters of the word in reverse order
for char in range(len(word) - 1, -1, -1):
    # Print each character from the word in reverse order without a new line (end="")
    print(word[char], end="")

# Print a new line to separate the reversed word from the next output
print("\n")

In [ ]:
a=np.random.randint(40,80,100)
print (a)

[57 49 72 53 47 68 76 48 66 64 60 70 57 72 62 79 71 72 63 64 73 61 66 55
 68 51 57 47 53 71 44 70 53 53 72 64 76 61 46 63 68 52 68 50 51 75 61 68
 48 65 74 51 65 65 44 61 69 40 70 47 73 74 61 74 69 47 70 70 52 51 79 79
 61 70 47 68 74 55 62 76 66 49 59 45 52 66 75 64 74 63 58 40 47 66 72 54
 59 66 43 77]


![image.png](attachment:a92a00d4-7af6-40f2-bc28-e533e7bfa23b.png)

In [ ]:
# Python program to demonstrate
# unary operators in numpy
arr = np.array([[1, 5, 6],
				[4, 7, 2],
				[3, 1, 9]])

# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:", arr.max(axis = 1))

# minimum element of array
print ("Column-wise minimum elements:", arr.min(axis = 0))

# sum of array elements
print ("Sum of all array elements:", arr.sum(axis=0))

# cumulative sum along each row
print ("Cumulative sum along each row:\n", arr.cumsum())

In [ ]:
# Python program to demonstrate
# binary operators in Numpy
a = np.array([[1, 2],
			[3, 4]])
b = np.array([[4, 3],
			[2, 1]])

# add arrays
print ("Array sum:\n", a + b)

# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)

# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))


In [ ]:
# universal functions in numpy

# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

# square root of array values
print ("Square root of array elements:", np.sqrt(a))


In [ ]:
# Python program to demonstrate sorting in numpy
a = np.array([[1, 4, 2],
				[3, 4, 6],
                [0, -1, 5]])

# sorted array
print ("Array elements in sorted order:\n", np.sort(a, axis = None)) # axis value : None, 0, 1, -1,-2

# sort array row-wise
print ("Row-wise sorted array:\n", np.sort(a, axis = -2))

# specify sort algorithm
print ("Column wise sort by applying merge-sort:\n", np.sort(a, axis = 0, kind = 'mergesort'))

# Example to show sorting of structured array
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithikkhkjfhajfhajfha', 2009, 8.5), ('Ajay', 2008, 8.7),
		('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n", np.sort(arr, order = 'name'))

print ("Array sorted by grauation year and then cgpa:\n", np.sort(arr, order = ['grad_year', 'cgpa']))

newstring = ['a10','A2','a4','a11','a18','a01']
print("Sorted array: ",np.sort(newstring,axis=0))

In [ ]:
#Numpy empty array creation

import numpy as np

x = np.empty([3,2],dtype='int')
print(x)

Numpy array can have different datatypes values

In [ ]:
import numpy as np
a = np.array([True, False, False, True])
a.dtype

dtype('bool')

In [ ]:
b = np.array(['Bonjour', 'Hello', 'Hallo'])
b.dtype     # <--- strings containing max. 7 letters

dtype('<U7')

# NumPy indexing and slicing

In [ ]:
a = np.arange(10)
print(a)
print("Value at 0th index: {} , \nValue at 2nd index: {} and \nValue at -1 index: {} ".format(a[0], a[2], a[-1]))
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
Value at 0th index: 0 , 
Value at 2nd index: 2 and 
Value at -1 index: 9 
[9 8 7 6 5 4 3 2 1 0]


# A small illustrated summary of NumPy indexing and slicing…

![image.png](attachment:image.png)

In [ ]:
#combine assignment and slicing:
a = np.arange(10)
a[5:] = 10
print("a = ",a)
b = np.arange(5)
print("b = ",b)
a[5:] = b[::-1]
print("a after operation = ",a)

a =  [ 0  1  2  3  4 10 10 10 10 10]
b =  [0 1 2 3 4]
a after operation =  [0 1 2 3 4 4 3 2 1 0]


In [ ]:
a = np.arange(6)
b = np.arange(0, 51, 10)[:, np.newaxis,np.newaxis]

c = np.arange(0,51,10)[np.newaxis,:]

print(a)
print(b)
print(c)
print(a.shape)
print(b.shape)
print(c.shape)

[0 1 2 3 4 5]
[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
[[ 0 10 20 30 40 50]]
(6,)
(6, 1)
(1, 6)


In [ ]:
#expand the dimention
a = np.arange(6).reshape(2, 3)
print(a)
# [[0 1 2]
#  [3 4 5]]

print(np.expand_dims(a, 0))

print(np.expand_dims(a, 0).shape)
# (1, 2, 3)

[[0 1 2]
 [3 4 5]]
[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)


In [ ]:
a + b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

### A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use np.may_share_memory() to check if two arrays share the same memory block.

In [ ]:
a = np.arange(10)
print("a : ",a)
b = a[::2]
print("b : ",b)
print(np.may_share_memory(a, b))
b[0] = 12
print("new b : ",b)
print("changed in variable a :",a)   # (!)
a = np.arange(10)
c = a[::2].copy()  # force a copy
c[0] = 12
print("a : ",a)
print(np.may_share_memory(a, c))
print("c : ",c)

In [ ]:
#Programming Example: Prime number from 0 to 100
is_prime = np.ones((100,), dtype=bool)
print(is_prime)
is_prime[:2] = 0
print(is_prime)
N_max = int(np.sqrt(len(is_prime) - 1))
print(N_max)
count=0
for j in range(2, N_max + 1):
    print("value of count variable: "+str(count))
    is_prime[2*j::j] = False
    print("value of j",j)
    print(is_prime)
    count+=1
is_prime[0]=is_prime[1]= 0
index = np.arange(0,100,1)
for i in range(100): print(str(index[i]) + ':' + str(is_prime[i]))

#### Write a code to fatch all the index whose value is true.

# Fancy indexing
NumPy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not views.

Using boolean masks

In [ ]:
# a[5]
np.random.seed(3)
a = np.random.randint(0, 21, 15)
print(a)
#(a % 3 == 0)
mask = (a % 3 == 0)
print(mask)
extract_from_a = a[mask] # or,  a[a%3==0]
extract_from_a

[10  3  8  0 19 10 11  9 10  6  0 20 12  7 14]
[False  True False  True False False False  True False  True  True False
  True False False]


array([ 3,  0,  9,  6,  0, 12])

In [ ]:
RollNo
6,23,73,25,35,34,36,65,96,99

In [ ]:
a[a % 3 == 0] = -1
print(a)

[10 -1  8 -1 19 10 11 -1 10 -1 -1 20 -1  7 14]


# Indexing with an array of integers

In [ ]:
a = np.arange(0, 100, 10)
print(a)
#indexing can be done with an array of integers, where the same index is repeated several time:
print(a[[2, 3, 2, 5, 2]] ) # note: [2, 3, 2, 4, 2] is a Python list
#New values can be assigned with this kind of indexing:
a[[9, 7]] = -100
print(a)
#When a new array is created by indexing with an array of integers, the new array has the same shape as the array of integers:
a = np.arange(10)
a = a**2
print(a)
idx = np.array([[3, 4], [9, 7]])
print(idx.shape)
print(a[idx])
print(a)

![image.png](attachment:image.png)

# Numerical operations

Comparisons: (Element-wise and Array-wise comparisons)

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1,2,3,4])
print(a == c)
print(a > b)

[ True  True  True  True]
[False False  True False]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
print(np.array_equal(a, b))
print(np.array_equal(a, c))

False
True


In [ ]:
a = np.arange(9).reshape((3, 3)) # [0 1 2 3 4 5 6 7 8]
print(a)
# [[0 1 2]
#  [3 4 5]
#  [6 7 8]]

print(np.where(a < 4, -100, 100))
# [[ -1  -1  -1]
#  [ -1 100 100]
#  [100 100 100]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-100 -100 -100]
 [-100  100  100]
 [ 100  100  100]]


### Logical Operations:

In [ ]:
print(np.all([True, True, True]))
print(np.any([False, True, False]))
print(np.all([1,0,5]))

True
True
False


In [ ]:
a = np.zeros((100, 100))
print(np.any(a != 0))
print(np.all(a == 0))
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 2])
print(((a <= b) & (b <= c)).all()) # [True True True True] & [True True True True]

False
True
True


Statistics:

In [ ]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
print(x.mean())
print(np.median(x))
print(np.median(y, axis=1))
print(np.median(y, axis=0)) # last axis
print(x.std())      # full population standard dev.

1.75
1.5
[2. 5.]
[3. 4. 2.]
0.82915619758885


# More data types
     Casting
     Structured data types

Casting

In [ ]:
#“Bigger” type wins in mixed-type operations:
a = np.array([1, 2, 3]) + 1.5
print(a)

[2.5 3.5 4.5]


In [ ]:
#Assignment never changes the type!
a = np.array([1, 2, 3])
print(a.dtype)
a[0] = 1.9     # <-- float is truncated to integer
print(a)

In [ ]:
#Forced casts:
a = np.array([1.7, 1.2, 1.6])
b = a.astype(int)  # <-- truncates to integer
print(b)

In [ ]:
#Rounding:
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
b = np.around(a)
print(b)                    # still floating-point
c = np.around(a).astype(int)
print(c)


Structured data types

In [ ]:
samples = np.zeros((6,), dtype=[('sensor_code', 'S4'),('position', float), ('value', float)])
print(samples.ndim)
print(samples.shape)
print(samples.dtype.names)
samples[:] = [('ALFA',   1, 0.37), ('BETA', 1, 0.11), ('TAU', 1,   0.13),
              ('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]
print(samples)

In [ ]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])

print("Our array is:",x)

rows = np.array([[0,0],[3,3]])         # [0,0,3,3]
cols = np.array([[0,2],[0,2]])         # [0,2,0,2]
y = x[rows,cols]

print('The corner elements of this array are:',y)


# Stacking:
    Several arrays can be stacked together along different axes.
    np.vstack: To stack arrays along vertical axis.
    np.hstack: To stack arrays along horizontal axis.
    np.column_stack: To stack 1-D arrays as columns into 2-D arrays.
    np.concatenate: To stack arrays along specified axis (axis is passed as argument).


In [ ]:
import numpy as np

a = np.array([[1, 2],
			[3, 4]])

b = np.array([[5, 6],
			[7, 8]])

# vertical stacking
print("Vertical stacking:\n", np.vstack((a, b)))

# horizontal stacking
print("\nHorizontal stacking:\n", np.hstack((a, b)))

c = [5, 6]

# stacking columns
print("\nColumn stacking:\n", np.column_stack((a, c)))

# concatenation method
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1))

# Splitting:
    For splitting, we have these functions:
    np.hsplit: Split array along horizontal axis.
    np.vsplit: Split array along vertical axis.
    np.array_split: Split array along specified axis.


In [ ]:
a = np.array([[1, 3, 5, 7, 9, 11],
			[2, 4, 6, 8, 10, 12]])

# horizontal splitting
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 3))

# vertical splitting
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))


# Linear algebra in NumPy
    
    The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array.
    Rank, determinant, trace, etc. of an array.
    Eigen values of matrices
    Matrix and vector products (dot, inner, outer,etc. product), matrix exponentiation
    Solve linear or tensor equations and much more!


In [ ]:
A = np.array([[6, 1, 1],
			[4, -2, 5],
			[2, 8, 7]])

print("Rank of A:", np.linalg.matrix_rank(A))

print("\nTrace of A:", np.trace(A))

print("\nDeterminant of A:", np.linalg.det(A))

print("\nInverse of A:\n", np.linalg.inv(A))

print("\nMatrix A raised to power 3:\n", np.linalg.matrix_power(A, 3))


In [ ]:
#Let us assume that we want to solve this linear equation set:
#x + 2*y = 8
#3*x + 4*y = 18
# coefficients
a = np.array([[1, 2], [3, 4]])
# constants
b = np.array([8, 18])

print("Solution of linear equations:", np.linalg.solve(a, b))


Solution of linear equations: [2. 3.]


# Array shape manipulation

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = np.array([1,2,3])
a = a.reshape(4,3)
print(a)
c = a + b
print(c.shape)
print(c)

In [ ]:
# simplest broadcasting example occurs when an array and a scalar value are combined in an operation

a = np.array([1.0, 2.0, 3.0])

# Example 1
b = 2.0
print(a * b)

# Example 2
c = [2.0, 2.0, 2.0]
print(a * c)


In [ ]:
#broadcasting example
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])

#x3 = x1+x2
#print(x3)

#add new axis
newx3 = x1[:,np.newaxis]
x3 = newx3+x2
print(x3)

In [ ]:
#example where both arrays get stretched
import numpy as np

a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([0.0, 1.0, 2.0])
a = a.reshape(4,1)
print(a + b)


![image.png](attachment:image.png)

![image.png](attachment:image.png)

In [ ]:
#Adding a dimension
z = np.array([1, 2, 3])
print(z)
print(z[:, np.newaxis])
print(z[np.newaxis, :])

In [ ]:
#Dimension shuffling
a = np.arange(4*3*2).reshape(4, 3,2)
print(a.shape)
print(a[0, 2, 1])
b = a.transpose(1,2,0)
print(b.shape)
print(b[2, 1, 0])

In [ ]:
#Resizing
a = np.arange(4)
a.resize(8)
print(a)

In [ ]:
#However, it must not be referred to somewhere else:
b = a
a.resize(4)
print(a)