In [ ]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
data=pd.read_csv('Iris.csv',header='infer').values
X=data[:,1:-1]
y=data[:,-1]
test_split=float(input('Enter the test size: '))
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=test_split,stratify = y)
k=int(input('Enter the number of clusters you want to divide in: '))
n=int(input('Enter number of iterations you want to run: '))
centroids=np.zeros(shape=(k,X_train.shape[1]))
per=np.random.permutation(X_train.shape[0])

Enter the test size: 0.2
Enter the number of clusters you want to divide in: 3
Enter number of iterations you want to run: 1


In [ ]:
for i in range(k):
  centroids[i,:]=X_train[per[i],:]
print(centroids)
for it in range(n):
  dist=np.zeros(shape=(k,X_train.shape[0]))
  # distance of each datapoint and centroid
for i in range(k):
  dist[i,:]=np.sqrt(np.sum((X_train-centroids[i])**2,axis=1))
  membership=np.argmin(dist,axis=0)
for i in range(k):
  centroids[i,:]=np.mean(X_train[membership==i,:],axis=0)
print(centroids)

[[6.  2.2 4.  1. ]
 [6.3 2.9 5.6 1.8]
 [6.  3.4 4.5 1.6]]
[[5.17068966 3.09310345 2.23448276 0.54655172]
 [6.65945946 2.96216216 5.61621622 2.02972973]
 [6.064      3.04       4.416      1.444     ]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

data = pd.read_csv('Iris.csv', header='infer').values
X = data[:, 1:-1]
y = data[:, -1]

test_split = float(input('Enter the test size: '))
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_split, stratify=y)

k = int(input('Enter the number of clusters you want to divide in: '))
n = int(input('Enter number of iterations you want to run: '))
centroids = np.zeros(shape=(k, X_train.shape[1]))
print(centroids)
per = np.random.permutation(X_train.shape[0])

for i in range(k):
    centroids[i, :] = X_train[per[i], :]

print(centroids)

for it in range(n):
    dist = np.zeros(shape=(k, X_train.shape[0]))
    for i in range(k):
        dist[i, :] = np.sqrt(np.sum((X_train - centroids[i]) ** 2, axis=1))
    membership = np.argmin(dist, axis=0)
    print(membership)
    for i in range(k):
        centroids[i, :] = np.mean(X_train[membership == i, :], axis=0)

print(centroids)


Enter the test size: 0.2
Enter the number of clusters you want to divide in: 3
Enter number of iterations you want to run: 3
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5.  3.2 1.2 0.2]
 [6.  2.2 5.  1.5]
 [4.5 2.3 1.3 0.3]]
[1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 1 0 1 1 0 1 1 1 0
 1 1 1 1 1 0 0 0 1 0 1 0 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 2 2 0 1 1 1 0 1 1 1 0 0 1 1 0 1 1 1
 1 1 0 0 0 1 1 1 1]
[1 0 1 0 1 1 0 0 1 1 2 0 1 0 0 0 0 0 2 1 0 1 0 1 0 1 0 1 1 0 2 1 0 2 1 1 0
 1 1 1 1 1 0 0 0 1 0 1 0 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 2 2 0 1 1 1 0 1 1 1 0 0 1 1 0 1 1 1
 1 1 0 0 0 1 1 1 1]
[1 0 1 0 1 1 0 0 1 1 2 0 1 0 0 0 0 0 2 2 0 1 0 1 0 1 0 1 1 0 2 2 0 2 1 1 0
 1 1 1 1 1 0 0 0 1 0 1 0 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0 1 1 1 1
 1 2 1 1 1 1 1 1 1 1 1 1 0 1 2 1 1 1 0 2 0 0 1 2 1 0 1 2 1 0 0 1 1 0 1 1 1
 1 2 0 0 0 1 1 1 1]
[[5.0075     3.4625     1.4575     0