In [ ]:
#K-means Clustering of IRIS Dataset

import numpy
from sklearn import datasets, metrics
from sklearn.cluster import KMeans

data, target=datasets.load_iris(return_X_y=True)

X_train=data[range(0,150,2),:]
X_test=data[range(1,150,2),:]

model=KMeans(n_clusters=3) #max_iter = 300

model.fit(X_train)

print(model.labels_)

prediction = model.predict(X_test)

print(prediction)

#prediction = numpy.choose(prediction, ['ir_se','ir_ve','ir_vr'])
#prediction = numpy.choose(prediction, [0,1,2]).astype(numpy.int64)

#print(prediction)



print(model.cluster_centers_)


#print(metrics.accuracy_score(target, prediction, normalize=True))

#print(metrics.confusion_matrix(target, prediction))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 2 2 2 2 2 2 2 2 2
 2 1 2 2 2 2 2 2 2 2 2 2 2 1 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 2 1 2 1 1
 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2
 2 1 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 2 1 1 2 2 2 1 2 1 1 1 1 1 1 1 1 1 1
 2]
[[5.024      3.48       1.456      0.228     ]
 [6.68333333 2.97916667 5.59583333 2.04166667]
 [5.84615385 2.74230769 4.32692308 1.41153846]]


In [ ]:
#MLPClassifier For IRIS Flower Classification
import numpy
from sklearn import datasets, metrics
from sklearn.neural_network import MLPClassifier

X, y=datasets.load_iris(return_X_y=True)

X_train=X[range(0,150,2),:]   #iris.data is numpy array
y_train=y[range(0,150,2)]

X_test=X[range(1,150,2),:]
y_test=y[range(1,150,2)]

clf = MLPClassifier(solver='sgd', hidden_layer_sizes=(65), max_iter=200) #creating instance of the classifier

# activation : {'identity', 'logistic', 'tanh', 'relu'}, default 'relu'
# learning_rate : {'constant', 'invscaling', 'adaptive'}, default 'constant'
#learning_rate_init : double, optional, default 0.001
# solver{'lbfgs', 'sgd', 'adam'}, default='adam'

clf.fit(X_train,y_train)
#print(clf.get_params())
prediction = clf.predict(X_test) #predict using the learnt classifier

print(prediction)
print(clf.predict_proba(X_test));
print(metrics.accuracy_score(y_test, prediction, normalize=True))
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
[[0.87555593 0.11331412 0.01112994]
 [0.84976878 0.13297598 0.01725524]
 [0.90429359 0.08744493 0.00826148]
 [0.89360572 0.09691034 0.00948394]
 [0.87438415 0.11422365 0.0113922 ]
 [0.86814913 0.11760702 0.01424385]
 [0.89453434 0.09452798 0.01093767]
 [0.95001255 0.0467938  0.00319365]
 [0.91118367 0.08153205 0.00728427]
 [0.91543177 0.07715848 0.00740975]
 [0.90528508 0.08601922 0.00869569]
 [0.83808732 0.14419648 0.0177162 ]
 [0.84782859 0.13767957 0.01449184]
 [0.90806925 0.08473005 0.0072007 ]
 [0.84589291 0.13638372 0.01772337]
 [0.89927115 0.09309593 0.00763292]
 [0.94904917 0.04768516 0.00326567]
 [0.91348446 0.08001553 0.0065    ]
 [0.91626425 0.07654662 0.00718913]
 [0.89811226 0.09337281 0.00851493]
 [0.79359073 0.18229532 0.02411395]
 [0.85963084 0.1243104  0.01605876]
 [0.86384836 0.12258252 0.01356912]
 [0.87487402 0.111

c:\users\priyank\appdata\local\programs\python\python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
import numpy as np
from sklearn import svm, datasets, metrics

X, y = datasets.load_iris(return_X_y=True)

X_train=X[range(0,150,2),:]
y_train=y[range(0,150,2)]

X_test=X[range(1,150,2),:]
y_test=y[range(1,150,2)]

clf = svm.LinearSVC() #creating instance of a classifier
# LinearSVC does not accept keyword kernel, as this is assumed to be linear.
# It also lacks some of the members of SVC and NuSVC
# dual: bool, (default=True)
# multi_class: str, ‘ovr’ or ‘crammer_singer’ (default=’ovr’)
# max_iter: int, (default=1000)


# or clf = svm.SVC() or clf = svm.NuSVC()
# regr = svm.LinearSVR() regr = svm.SVC() or regr = svm.NuSVR #()in case of regression
# SVC and NuSVC use 'ovo' (one vs one) strategy. It is the only option availalbe
# in SVC and NuSVC for multiclass classification.

clf.fit(X_train, y_train)

prediction = clf.predict(X_test) #predict using the learnt classifier

print(prediction)
print(metrics.accuracy_score(y_test, prediction, normalize=True))
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 1 2 2 2 2 2 2 2
 2]
0.96
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75

[[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]


c:\users\priyank\appdata\local\programs\python\python38\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [ ]:
import numpy
from sklearn import neighbors, datasets, metrics
from sklearn.model_selection import GridSearchCV

X, y=datasets.load_iris(return_X_y=True) #Loading the Iris Dataset

X_train=X[range(0,150,2),:]
y_train=y[range(0,150,2)]

X_test=X[range(1,150,2),:]
y_test=y[range(1,150,2)]

#creating instance of a classifier
clf = neighbors.KNeighborsClassifier()

#param_grid should be dictionary or list of dictionaries
#Specify hyperparameters which you want to tune

#If some hyperparameter you don't want to tune, specify that parameter
#while creating instance of the classifier

param_grid = {'n_neighbors': [1, 5, 10, 20], 'weights': ['uniform', 'distance']}

clf_gs=GridSearchCV(clf,param_grid,cv=5)
#there is a refit argument whose default is True

clf_gs.fit(X_train, y_train)

#Print best parameters
print(clf_gs.best_params_)

prediction = clf_gs.predict(X_test) #predict using the learnt classifier

print("############### Predictions #################")
print(prediction)
print("#############################################")

print("Accuracy = ", metrics.accuracy_score(y_test, prediction, normalize=True))

print(metrics.classification_report(y_test, prediction))

print(metrics.confusion_matrix(y_test, prediction))

{'n_neighbors': 5, 'weights': 'uniform'}
############### Predictions #################
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
#############################################
Accuracy =  0.9866666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      0.96      0.98        25
           2       0.96      1.00      0.98        25

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75

[[25  0  0]
 [ 0 24  1]
 [ 0  0 25]]
