In [4]:
import pandas as pd
from google.colab import files
uploaded = files.upload()
import io df2 = pd.read_csv(io.BytesIO(uploaded['cancer_dataset.csv']))
# Dataset is now stored in a Pandas Dataframe

Saving cancer_dataset.csv to cancer_dataset (1).csv


In [7]:
print(cancer_dataset["Status"].value_counts())
cancer_dataset["Status"].value_counts().plot(kind="bar")

NameError: ignored

## Converting categorical variable to numerical variable

In [ ]:
cancer_dataset.info()

NameError: ignored

In [ ]:
for col in cancer_dataset.columns:
  if cancer_dataset[col].dtype==object:
    print(col)
    print(cancer_dataset[col].unique())

In [ ]:
cancer_dataset

In [3]:
cancer_dataset["Status"] = cancer_dataset["Status"].replace({"Alive":0,"Dead":1})
cancer_dataset["Progesterone Status"] = cancer_dataset["Progesterone Status"].replace({"Positive":0,"Negative":1})
cancer_dataset["Estrogen Status"] = cancer_dataset["Estrogen Status"].replace({"Positive":0,"Negative":1})
cancer_dataset["A Stage"] = cancer_dataset["A Stage"].replace({"Regional":0,"Distant":1})
cancer_dataset["Grade"] = cancer_dataset["Grade"].replace({"Well differentiated; Grade I":0,"Moderately differentiated; Grade II":1,"Poorly differentiated; Grade III":2,"Undifferentiated; anaplastic; Grade IV":3})
#cancer_dataset["Race"] = cancer_dataset["Race"].replace({"White":0,"Black":1,"Other (American Indian/AK Native, Asian/Pacific Islander)":2})
cancer_dataset["Marital Status"] = cancer_dataset["Marital Status"].replace({'Married (including common law)':0,'Divorced':1,'Single (never married)':2,
'Widowed':3,'Separated':4})
#cancer_dataset["T Stage"] = cancer_dataset["T Stage"].replace({'T2':1,'T1':0,'T3':2,'T4':3})
cancer_dataset["N Stage"] = cancer_dataset["N Stage"].replace({'N3':2,'N2':1,'N1':0})
cancer_dataset["6th Stage"] = cancer_dataset["6th Stage"].replace({'IIIC':4,'IIIA':2,'IIB':1,'IIA':0,'IIIB':3})
print(cancer_dataset.head())

NameError: ignored

In [5]:
cancer_dataset.head()

NameError: ignored

Dropping unnamed col

## Data splitting

In [ ]:
from sklearn.model_selection import train_test_split

X = cancer_dataset.drop("Status",axis=1)
y = cancer_dataset["Status"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.3)

## Data Standardizing

In [ ]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.fit_transform(X_test)
print(X_train)

## Model building

In [ ]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier

### Without balancing data

Linear SVM

In [ ]:
svc = SVC() ###rbf is default kernel
clf = svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

NameError: ignored

Logistic Reg

In [ ]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

NameError: ignored

Naiva bayes - GaussianNb

In [ ]:
gb = GaussianNB()
gb.fit(X_train,y_train)
y_pred = gb.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

DecisionTreeClassifier

In [ ]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)
y_pred = dtree.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

## Random Oversampling

In [ ]:
from imblearn.over_sampling import RandomOverSampler
oversample = RandomOverSampler(sampling_strategy='minority')
X_train_over, y_train_over = oversample.fit_resample(X_train, y_train)

In [ ]:
np.unique(y_train_over,return_counts=True)

In [ ]:
X_train_over = scalar.fit_transform(X_train_over)
X_test = scalar.fit_transform(X_test)

In [ ]:
clf = svc.fit(X_train_over,y_train_over)
y_pred = svc.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print()
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Logistic Reg

In [ ]:
lr.fit(X_train_over,y_train_over)
y_pred = lr.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Naiva bayes - GaussianNb

In [ ]:
gb.fit(X_train_over,y_train_over)
y_pred = gb.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

DecisionTreeClassifier

In [ ]:
dtree.fit(X_train_over,y_train_over)
y_pred = dtree.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

## SMOTE

In [ ]:
from imblearn.over_sampling import SMOTE
oversample = SMOTE()
X_train_smote, y_train_smote = oversample.fit_resample(X_train, y_train)

In [ ]:
np.unique(y_train_smote,return_counts=True)

In [ ]:
X_train_smote = scalar.fit_transform(X_train_smote)
X_test = scalar.fit_transform(X_test)

In [ ]:
clf = svc.fit(X_train_smote,y_train_smote)
y_pred = svc.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print()
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Logistic regression

In [ ]:
lr.fit(X_train_smote,y_train_smote)
y_pred = lr.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Confusion Matrix: 
[[616 400]
 [ 19 173]]
Classifiction Report :
              precision    recall  f1-score   support

           0       0.97      0.61      0.75      1016
           1       0.30      0.90      0.45       192

    accuracy                           0.65      1208
   macro avg       0.64      0.75      0.60      1208
weighted avg       0.86      0.65      0.70      1208



Naive bayes

In [ ]:
gb.fit(X_train_smote,y_train_smote)
y_pred = gb.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Confusion Matrix: 
[[790 226]
 [ 56 136]]
Classifiction Report :
              precision    recall  f1-score   support

           0       0.93      0.78      0.85      1016
           1       0.38      0.71      0.49       192

    accuracy                           0.77      1208
   macro avg       0.65      0.74      0.67      1208
weighted avg       0.85      0.77      0.79      1208



Decision Tree classifier

In [ ]:
dtree.fit(X_train_smote,y_train_smote)
y_pred = dtree.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Confusion Matrix: 
[[338 678]
 [ 48 144]]
Classifiction Report :
              precision    recall  f1-score   support

           0       0.88      0.33      0.48      1016
           1       0.18      0.75      0.28       192

    accuracy                           0.40      1208
   macro avg       0.53      0.54      0.38      1208
weighted avg       0.76      0.40      0.45      1208



## Borderline SMOTE

In [ ]:
from imblearn.over_sampling import BorderlineSMOTE
oversample = BorderlineSMOTE()
X_train_border_smote, y_train_border_smote = oversample.fit_resample(X_train, y_train)

In [ ]:
np.unique(y_train_border_smote,return_counts=True)

In [ ]:
X_train_border_smote = scalar.fit_transform(X_train_border_smote)
X_test = scalar.fit_transform(X_test)

In [ ]:
clf = svc.fit(X_train_border_smote,y_train_border_smote)
y_pred = svc.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print()
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Logistic regression

In [ ]:
lr.fit(X_train_border_smote,y_train_border_smote)
y_pred = lr.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Naive bayes

In [ ]:
gb.fit(X_train_border_smote,y_train_border_smote)
y_pred = gb.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Decision Tree classifier

In [ ]:
dtree.fit(X_train_border_smote,y_train_border_smote)
y_pred = dtree.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

### ADASYN

In [ ]:
from imblearn.over_sampling import ADASYN
oversample = ADASYN()
X_train_adasyn, y_train_adasyn = oversample.fit_resample(X_train, y_train)

In [ ]:
np.unique(y_train_adasyn,return_counts=True)

In [ ]:
X_train_adasyn = scalar.fit_transform(X_train_adasyn)
X_test = scalar.fit_transform(X_test)

In [ ]:
clf = svc.fit(X_train_adasyn,y_train_adasyn)
y_pred = svc.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print()
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Logistic regression

In [ ]:
lr.fit(X_train_adasyn,y_train_adasyn)
y_pred = lr.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Naive bayes

In [ ]:
gb.fit(X_train_adasyn,y_train_adasyn)
y_pred = gb.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))

Decision Tree classifier

In [ ]:
dtree.fit(X_train_adasyn,y_train_adasyn)
y_pred = dtree.predict(X_test)
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("Classifiction Report :")
print(classification_report(y_test, y_pred))