In [ ]:
 from sklearn.feature_extraction.text import CountVectorizer

# Sample documents
documents = [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one.",
    "Is this the first document?"
]

# Create an instance of CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the documents
X = vectorizer.fit_transform(documents)

# Convert the result to an array
X_array = X.toarray()

# Get the vocabulary (unique words)
vocab = vectorizer.get_feature_names_out()

print("Vocabulary:", vocab)
print("Document-Term Matrix:\n",X_array)

Vocabulary: ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
Document-Term Matrix:
 [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [ ]:
import pandas as pd

url= 'https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv'

sms = pd.read_table(url, header=None, names=['label', 'message'])
print(sms.shape)
print(sms.head(5))
sms.label.value_counts()
print(sms.label.value_counts())
sms['label_num'] = sms.label.map({'ham':0, 'spam':1})
sms.head()
X = sms.message
y = sms.label_num
print("Shape of X: ",X.shape)
print("Shape of Y: ",y.shape)
X_train = X[0:4179]
X_test = X[4179:]
y_train = y[0:4179]
y_test = y[4179:]
print("Shape of X_train: ",X_train.shape)
print("Shape of X_test: ",X_test.shape)
print("Shape of y_train: ",y_train.shape)
print("Shape of y_test: ",y_test.shape)


(5572, 2)
  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
ham     4825
spam     747
Name: label, dtype: int64
Shape of X:  (5572,)
Shape of Y:  (5572,)
Shape of X_train:  (4179,)
Shape of X_test:  (1393,)
Shape of y_train:  (4179,)
Shape of y_test:  (1393,)


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
# The CountVectorizer is a class in scikit-learn lib used converting a collection
# of text documents to a matrix of token counts.
# learn training data vocabulary, then use it to create a document-term matrix
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)
X_test_dtm = vect.transform(X_test)
print(X_train_dtm)


  (0, 901)	1
  (0, 1106)	1
  (0, 1490)	1
  (0, 1492)	1
  (0, 1744)	1
  (0, 1977)	1
  (0, 3048)	1
  (0, 3087)	1
  (0, 3116)	1
  (0, 3509)	1
  (0, 3741)	1
  (0, 3853)	1
  (0, 4773)	1
  (0, 5107)	1
  (0, 6596)	1
  (0, 6939)	1
  (0, 7146)	1
  (0, 7349)	1
  (1, 3712)	1
  (1, 3883)	1
  (1, 4743)	1
  (1, 4769)	1
  (1, 7257)	1
  (2, 65)	1
  (2, 337)	1
  :	:
  (4176, 5633)	1
  (4176, 6578)	2
  (4176, 7180)	1
  (4176, 7459)	2
  (4177, 1516)	1
  (4177, 3241)	1
  (4177, 3509)	2
  (4177, 3743)	1
  (4177, 3776)	1
  (4177, 3864)	1
  (4177, 4910)	1
  (4177, 5676)	1
  (4177, 6000)	1
  (4177, 6568)	1
  (4177, 6575)	1
  (4177, 6578)	1
  (4177, 6700)	1
  (4177, 6759)	1
  (4177, 7163)	1
  (4178, 3048)	1
  (4178, 4060)	2
  (4178, 4743)	1
  (4178, 6591)	1
  (4178, 6707)	1
  (4178, 7163)	1


In [ ]:
from sklearn.naive_bayes import MultinomialNB

# 2. instantiate a Multinomial Naive Bayes model
nb = MultinomialNB()
%time nb.fit(X_train_dtm, y_train)

CPU times: user 2.76 ms, sys: 699 µs, total: 3.46 ms
Wall time: 10.5 ms


MultinomialNB()

In [ ]:
from sklearn import metrics
y_pred_class = nb.predict(X_test_dtm)
print("Accuracy: ",metrics.accuracy_score(y_test, y_pred_class))


Accuracy:  0.9856424982053122


In [ ]:
# examine class distribution
print(y_test.value_counts())
metrics.confusion_matrix(y_test, y_pred_class)
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(binary=True)
# learn training data vocabulary, then use it to create a document-term matrix
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)
X_train_dtm
X_test_dtm = vect.transform(X_test)
X_test_dtm


0    1211
1     182
Name: label_num, dtype: int64


<1393x7496 sparse matrix of type '<class 'numpy.int64'>'
	with 17049 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.naive_bayes import BernoulliNB
# 2. instantiate a BernoulliNB Naive Bayes model
nb = BernoulliNB()
%time nb.fit(X_train_dtm, y_train)
y_pred_class = nb.predict(X_test_dtm)
from sklearn import metrics
print("Accuracy: ",metrics.accuracy_score(y_test, y_pred_class))


CPU times: user 4.75 ms, sys: 516 µs, total: 5.27 ms
Wall time: 6.47 ms
Accuracy:  0.9763101220387652


In [ ]:
# examine class distribution
print(y_test.value_counts())
metrics.confusion_matrix(y_test, y_pred_class)


0    1211
1     182
Name: label_num, dtype: int64


array([[1210,    1],
       [  32,  150]])

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
# learn training data vocabulary, then use it to create a document-term matrix
vect.fit(X_train)

X_train_dtm = vect.transform(X_train)
X_test_dtm = vect.transform(X_test)
X_test_dtm
from sklearn.naive_bayes import GaussianNB
nb = BernoulliNB()
%time nb.fit(X_train_dtm, y_train)
y_pred_class = nb.predict(X_test_dtm)
print("Score: ",nb.score(X_test_dtm,y_test))
from sklearn import metrics
print("Accuracy: ",metrics.accuracy_score(y_test, y_pred_class))


CPU times: user 2.39 ms, sys: 81 µs, total: 2.47 ms
Wall time: 2.48 ms
Score:  0.9763101220387652
Accuracy:  0.9763101220387652


In [ ]:
 # examine class distribution
print(y_test.value_counts())
metrics.confusion_matrix(y_test, y_pred_class)


0    1211
1     182
Name: label_num, dtype: int64


array([[1210,    1],
       [  32,  150]])