In [ ]:
print("HelloWorld")
a=5
b=2
print(a)
print(a,b)
print(a)
print(b)
print("Valueofa=",a)
print("Valueofb=",b)

HelloWorld
5
5 2
5
2
Valueofa= 5
Valueofb= 2


In [ ]:
str='HelloWorld!'
print(str)
print(str[0])
print(str[2:5])
print(str[2:])
print(str*2)
print(str+"TEST")

HelloWorld!
H
llo
lloWorld!
HelloWorld!HelloWorld!
HelloWorld!TEST


In [ ]:
str='HelloWorld!'
print(str[-1])
print(str[-3:-1])
print(str[-12:])

!
ld
HelloWorld!


In [ ]:
list=['abcd',786,2.23,'john',70.2]
tinylist=[123,'john']
print(list)
print(list[0])
print(list[1:3])
print(list[2:])
print(tinylist*2)
print(list+tinylist)

['abcd', 786, 2.23, 'john', 70.2]
abcd
[786, 2.23]
[2.23, 'john', 70.2]
[123, 'john', 123, 'john']
['abcd', 786, 2.23, 'john', 70.2, 123, 'john']


In [ ]:
tuple=('abcd',786,2.23,'john',70.2)
tinytuple=(123,'john')
print(tuple)
print(tuple[0])
print(tuple[1:3])
print(tuple[2:])
print(tinytuple*2)
print(tuple+tinytuple)

('abcd', 786, 2.23, 'john', 70.2)
abcd
(786, 2.23)
(2.23, 'john', 70.2)
(123, 'john', 123, 'john')
('abcd', 786, 2.23, 'john', 70.2, 123, 'john')


In [ ]:
dict={}
dict['one']="Thisisone"
dict[2]="Thisistwo"
tinydict={'name':'john','code':6734,'dept':'sales'}
print(dict['one'])
print(dict[2])
print(tinydict)
print(tinydict.keys())
print(tinydict.values())

Thisisone
Thisistwo
{'name': 'john', 'code': 6734, 'dept': 'sales'}
dict_keys(['name', 'code', 'dept'])
dict_values(['john', 6734, 'sales'])


In [ ]:
var1=100
if var1:
  print("1-Got a true expression value")
  print(var1)
var2=0
if var2:
  print("2-Gotatrueexpressionvalue")
  print(var2)
print("Goodbye!")

1-Got a true expression value
100
Goodbye!


In [ ]:
amount=int(input("Enteramount:"))
if amount<1000:
  discount=amount*0.05
  print("Discount",discount)
else:
  discount=amount*0.10
  print("Discount",discount)
print("Netpayable:",amount-discount)

Enteramount:600
Discount 30.0
Netpayable: 570.0


In [ ]:
amount=int(input("Enteramount:"))
if amount<1000:
  discount=amount*0.05
  print("Discount",discount)
elif amount<5000:
  discount=amount*0.10
  print("Discount",discount)
else:
  discount=amount*0.15
  print("Discount",discount)
print("Netpayable:",amount-discount)

Enteramount:1500
Discount 150.0
Netpayable: 1350.0


In [ ]:
num=int(input("enternumber"))
if num%2==0:
  if num%3==0:
    print("Divisible by 3 and 2")
  else:
    print("divisible by 2 not divisible by 3")
else:
  if num%3==0:
    print("divisible by 3 not divisible by 2")
  else:
    print("not Divisible by 2 not divisible by 3")

enternumber4
divisible by 2 not divisible by 3


In [ ]:
count=0
while count<9 :
  print('Thecountis:',count)
  count=count+1

print("Goodbye!")

Thecountis: 0
Thecountis: 1
Thecountis: 2
Thecountis: 3
Thecountis: 4
Thecountis: 5
Thecountis: 6
Thecountis: 7
Thecountis: 8
Goodbye!


In [ ]:
for var in range(5):
  print(var)

0
1
2
3
4


In [ ]:
for letter in 'Python' :
  print('CurrentLetter:',letter)

CurrentLetter: P
CurrentLetter: y
CurrentLetter: t
CurrentLetter: h
CurrentLetter: o
CurrentLetter: n


In [ ]:
fruits=['banana','apple','mango']
for fruit in fruits :
  print('Currentfruit:',fruit)

Currentfruit: banana
Currentfruit: apple
Currentfruit: mango


In [ ]:
fruits=['banana','apple','mango']
for index in range(len(fruits)):
  print('Currentfruit:',fruits[index])
print("Goodbye!")

Currentfruit: banana
Currentfruit: apple
Currentfruit: mango
Goodbye!


In [ ]:
for letter in 'Python' :
  if letter=='h':
    break
  print('CurrentLetter:',letter)

CurrentLetter: P
CurrentLetter: y
CurrentLetter: t


In [ ]:
for letter in 'Python':
  if letter=='h':
    continue
  print('CurrentLetter:',letter)

CurrentLetter: P
CurrentLetter: y
CurrentLetter: t
CurrentLetter: o
CurrentLetter: n


In [ ]:
numbers=[11,33,55,39,55,75,37,21,23,41,13]
for num in numbers:
  if num%2==0:
    print('thelistcontainsanevennumber')
    breaK
else:
  print('the list does not contain even number')

the list does not contain even number


In [ ]:
list=['physics','chemistry',1997,2000]
print(list)
del list[2]
print("After deleting value at index 2 :",list)

['physics', 'chemistry', 1997, 2000]
After deleting value at index 2 : ['physics', 'chemistry', 2000]


In [ ]:
def changeme(mylist):
  "This changes a passed list into this function"
  print("Values inside the function before change:",mylist)
  mylist[2]=50
  print("Values inside the function after change :",mylist)
  return
mylist=[10,20,30]
changeme(mylist)
print("Values outside the function:",mylist)

Values inside the function before change: [10, 20, 30]
Values inside the function after change : [10, 20, 50]
Values outside the function: [10, 20, 50]


In [ ]:
def changeme(mylist):
  "This changes a Passed list into this function"
  mylist=[1,2,3,4]
  print("Values inside the function:",mylist)
  return
mylist=[10,20,30]
changeme(mylist)
print("Values outside the function:",mylist)

Values inside the function: [1, 2, 3, 4]
Values outside the function: [10, 20, 30]


In [ ]:
total=0
def sum(arg1,arg2):
  total=arg1+arg2;
  print("Inside the function local total:",total)
  return
sum(10,20)
print("Outside the function global total:",total)

Inside the function local total: 30
Outside the function global total: 0


In [ ]:
total=0
def sum(arg1,arg2):
  global total
  total=arg1+arg2;
  print("Inside the function local total:",total)
  return
sum(10,20)
print("Outside the function global total:",total)

Inside the function local total: 30
Outside the function global total: 30


In [ ]:
import numpy as np
a = np.array([1,4,5,8], float)
print(a)
print(type(a))

[1. 4. 5. 8.]
<class 'numpy.ndarray'>


In [ ]:
print(a[:2])
print(a[3])
a[0] = 5
print(a)

[1. 4.]
8.0
[5. 4. 5. 8.]


In [ ]:
a = np.array([[1,2,3],[4,5,6]], float)
print(a)
print(a[0,0])
print(a[0,1])
print(a[1,:])
print(a[:,2])
print(a[-1:,-2:])
print(a.shape)
print(a.dtype)
print(len(a))

[[1. 2. 3.]
 [4. 5. 6.]]
1.0
2.0
[4. 5. 6.]
[3. 6.]
[[5. 6.]]
(2, 3)
float64
2


In [ ]:
a = np.array(range(10), float)
print(a)
a = a.reshape((5,2))
print(a)
print(a.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
(5, 2)


In [ ]:
a = np.array([1,2,3], float)
b = a
c = a.copy()
a[0] = 0
print(a)
print(b)
print(c)

[0. 2. 3.]
[0. 2. 3.]
[1. 2. 3.]


In [ ]:
a = np.array(range(6), float).reshape((2,3))
print(a)
print(a.transpose())

[[0. 1. 2.]
 [3. 4. 5.]]
[[0. 3.]
 [1. 4.]
 [2. 5.]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]], float)
print(a)
print(a.flatten())

[[1. 2. 3.]
 [4. 5. 6.]]
[1. 2. 3. 4. 5. 6.]


In [ ]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
print(np.concatenate((a,b,c)))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[5,6],[7,8]], float)
print(np.concatenate((a,b)))
print(np.concatenate((a,b), axis = 0))
print(np.concatenate((a,b), axis = 1))

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [ ]:
print(np.arange(5,dtype = float))
print(np.arange(1,6,2, dtype = int))
print(np.ones((2,3), dtype = float))
print(np.zeros(7, dtype = int))

[0. 1. 2. 3. 4.]
[1 3 5]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 0 0 0 0 0 0]


In [ ]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
print(a+b)
print(a-b)
print(a*b)
print(b/a)
print(a%b)
print(b**a)

[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]
[5. 1. 2.]
[1. 0. 3.]
[  5.   4. 216.]


In [ ]:
a = np.array([[1,2],[3,4]], float)
b = np.array([[2,0], [1,3]], float)
print(a*b)

[[ 2.  0.]
 [ 3. 12.]]


In [ ]:
a = np.array([1,2,3], float)
b = np.array([4,5], float)
print(a+b)

ValueError: ignored

In [ ]:
a = np.array([[1,2],[3,4],[5,6]], float)
b = np.array([-1,3], float)
print(a)
print(b)
print(a + b)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[-1.  3.]
[[0. 5.]
 [2. 7.]
 [4. 9.]]


In [ ]:
a = np.zeros((2,2), float)
b = np.array([-1,3], float)
print(a)
print(b)
print(a+b)
print(a + b[np.newaxis,:])
print(a + b[:,np.newaxis])

[[0. 0.]
 [0. 0.]]
[-1.  3.]
[[-1.  3.]
 [-1.  3.]]
[[-1.  3.]
 [-1.  3.]]
[[-1. -1.]
 [ 3.  3.]]


In [ ]:
a = np.array([1,4,9], float)
print(np.sqrt(a))

[1. 2. 3.]


In [ ]:
a = np.array([1.1, 1.5, 1.9], float)
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))
print(np.pi)
print(np.e)

[1. 1. 1.]
[2. 2. 2.]
[1. 2. 2.]
3.141592653589793
2.718281828459045


In [ ]:
a = np.array([1,4,5], float)
for x in a:
  print(x)

1.0
4.0
5.0


In [ ]:
a = np.array([[1,2], [3,4], [5,6]], float)
for x in a :
  print(x)
for (x,y) in a :
  print(x*y)

[1. 2.]
[3. 4.]
[5. 6.]
2.0
12.0
30.0


In [ ]:
a = np.array([2,8,5], float)
print(np.sum(a))
print(np.mean(a))
print(np.prod(a))

15.0
5.0
80.0


In [ ]:
a = np.array([[1,2],[3,4]])
print(np.mean(a))
print(np.mean(a, axis = 0))
print(np.mean(a, axis = 1))
print(np.sort(a))
print(np.sort(a, axis = 0))
print(np.sort(a, axis = 1))

2.5
[2. 3.]
[1.5 3.5]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [ ]:
a = np.array([1,3,0], float)
b = np.array([0,3,2], float)
print(a>b)
print(a==b)
print(a<=b)
c = a>b
print(c)
print(a>2)

[ True False False]
[False  True False]
[False  True  True]
[ True False False]
[False  True False]


In [ ]:
c = np.array([True, False, False], bool)
print(any(c))
print(all(c))

True
False


In [ ]:
a = np.array([1,3,0], float)
print(np.where(a!=0, 1/a,a))
print(np.where(a>0, 3,2))

[1.         0.33333333 0.        ]
[3 3 2]


<ipython-input-57-d67c1d6315f5>:2: RuntimeWarning: divide by zero encountered in true_divide
  print(np.where(a!=0, 1/a,a))


In [ ]:
a = np.array([1,np.NaN, np.Inf], float)
print(a)
print(np.isnan(a))
print(np.isfinite(a))

[ 1. nan inf]
[False  True False]
[ True False False]


In [ ]:
a = np.array([[6,4], [5,9]], float)
print(a>=6)
print(a[a>=6])
sel = (a>=6)
print(a[sel])

[[ True False]
 [False  True]]
[6. 9.]
[6. 9.]


In [ ]:
a = np.array([1,2,3], float)
b = np.array([0,1,1], float)
print(np.dot(a,b))

5.0


In [ ]:
a = np.array([[0,1], [2,3]], float)
b = np.array([2,3], float)
c = np.array([[1,1], [4,0]], float)
print(a)
print(np.dot(b,a))
print(np.dot(a,b))
print(np.dot(a,c))
print(np.dot(c,a))

[[0. 1.]
 [2. 3.]]
[ 6. 11.]
[ 3. 13.]
[[ 4.  0.]
 [14.  2.]]
[[2. 4.]
 [0. 4.]]


In [ ]:
a = np.array([1,4,0], float)
b = np.array([2,2,1], float)
print(np.cross(a,b))

[ 4. -1. -6.]


In [ ]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float)
print(np.median(a))

3.0


In [ ]:
a = np.array([[1,2,1,3], [5,3,1,8]], float)
c = np.corrcoef(a)
print(c)
print(np.cov(a))

[[1. 2. 1. 3.]
 [5. 3. 1. 8.]]


In [ ]:
print(np.random.rand(5))
print(np.random.rand(2,3))
print(np.random.rand(6).reshape(2,3))
print(np.random.random())
print(np.random.randint(5,10))

[0.12556527 0.06682768 0.71650093 0.89389199 0.9063348 ]
[[0.84785555 0.0107099  0.89250721]
 [0.1755294  0.90164986 0.12020573]]
[[0.38925607 0.92349155 0.07971901]
 [0.18296062 0.44963445 0.99780868]]
0.9186869869563457
8


In [ ]:
x = np.arange(10)
np.save('outfile',x)
x = np.load('outfile.npy')
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x = np.arange(10)
y = np.random.randint(1,10, (2,3))
np.savez('outfile',x,y)
dict = np.load('outfile.npz')
x = dict['arr_0']
y = dict['arr_1']
print(x,y)

[0 1 2 3 4 5 6 7 8 9] [[8 4 1]
 [1 1 7]]
