In [ ]:
#
#TSP using BruteForce approach
#Read the data
import pandas as pd
import time #for measuring time
mat=pd.read_csv('/content/11citytsp.csv', header=None).values
#Checking
print(mat)
print(mat.dtype)
from itertools import permutations # module (itertools) permutations(functions) for generating every possible tour
citynames=list(range(mat.shape[0])) #city names, for simplicity 0 to no of rows in mat #cities-1
per=permutations(citynames) #generating permutations, return type is itertools.perm
print(type(per)) #checking
per=list(per) #converting to list of tuples
print(type(per)) #now list
#print(per) #checking
import numpy as np
st=time.process_time() #records the current value of the CPU time as a floating-point
#number of seconds using the time.process_time() function, and assigns the result to the variable st.
besttourlength=np.inf #initially postive infinity
for tour in per: #examining 1 tour at a time
    tourlength=0 #initial length of the tour being examined
    for i in range(len(tour)-1): #len(tour)-1 because last path will be back to sta
        tourlength+=mat[tour[i],tour[i+1]]
    tourlength+=mat[tour[i+1],tour[0]]
   # tourlength+=mat[startcity,] #lastcity to the startcity
    if tourlength < besttourlength:#minimum logic
      besttourlength=tourlength
      besttour=tour
et=time.process_time()
time_taken_ms=(et-st)*1000
print("Best Tour:", besttour)
print("Best Tour's Length:", besttourlength)
print("Time Taken:",time_taken_ms)

[[  0 633 257  91 412 150  80 134 259 505 353]
 [633   0 390 661 227 488 572 530 555 289 282]
 [257 390   0 228 169 112 196 154 372 262 110]
 [ 91 661 228   0 383 120  77 105 175 476 324]
 [412 227 169 383   0 267 351 309 338 196  61]
 [150 488 112 120 267   0  63  34 264 360 208]
 [ 80 572 196  77 351  63   0  29 232 444 292]
 [134 530 154 105 309  34  29   0 249 402 250]
 [259 555 372 175 338 264 232 249   0 495 352]
 [505 289 262 476 196 360 444 402 495   0 154]
 [353 282 110 324  61 208 292 250 352 154   0]]
int64
<class 'itertools.permutations'>
<class 'list'>
Best Tour: (0, 3, 8, 4, 1, 9, 10, 2, 5, 7, 6)
Best Tour's Length: 1639
Time Taken: 221838.05147199996


In [4]:
import pandas as pd
import time #for measuring time
mat=pd.read_csv('/content/11citytsp.csv', header=None).values
#Checking
print(mat)
print(mat.dtype)
from itertools import permutations
 # module (itertools) permutations(functions) for generating every possible tour
citynames=list(range(mat.shape[0]))
 #city names, for simplicity 0 to no of rows in mat #cities-1
per=permutations(citynames)
 #generating permutations, return type is itertools.perm
print(type(per)) #checking
per=list(per) #converting to list of tuples
print(type(per)) #now list
#print(per) #checking
import numpy as np
st=time.process_time()
 #records the current value of the CPU time as a floating-point
#number of seconds using the time.process_time() function,
#and assigns the result to the variable st.

besttourlength=np.inf #initially postive infinity
for tour in per: #examining 1 tour at a time
  tourlength=0 #initial length of the tour being examined
  for i in range(len(tour)-1):
    #len(tour)-1 because last path will be back to sta
      tourlength+=mat[tour[i],tour[i+1]]
  tourlength+=mat[tour[i+1],tour[0]] #lastcity to the startcity
  if tourlength < besttourlength: #minimum logic
    besttourlength=tourlength
    besttour=tour
et=time.process_time()
time_taken_ms=(et-st)*1000
print("Best Tour:", besttour)
print("Best Tour's Length:", besttourlength)
print("Time Taken:",time_taken_ms)

[[  0 633 257  91 412 150  80 134 259 505 353]
 [633   0 390 661 227 488 572 530 555 289 282]
 [257 390   0 228 169 112 196 154 372 262 110]
 [ 91 661 228   0 383 120  77 105 175 476 324]
 [412 227 169 383   0 267 351 309 338 196  61]
 [150 488 112 120 267   0  63  34 264 360 208]
 [ 80 572 196  77 351  63   0  29 232 444 292]
 [134 530 154 105 309  34  29   0 249 402 250]
 [259 555 372 175 338 264 232 249   0 495 352]
 [505 289 262 476 196 360 444 402 495   0 154]
 [353 282 110 324  61 208 292 250 352 154   0]]
int64
<class 'itertools.permutations'>
<class 'list'>


KeyboardInterrupt: 

In [5]:
#Again, bruteforce but this time, we are going to scan the start city
#Read the data
import pandas as pd
import time
mat=pd.read_csv("/content/11citytsp.csv", header=None).values
#Checking
print(mat)
from itertools import permutations
#asking for the starting city
startcity=int(input("Enter the start city from 0 to " + str(mat.shape[0]-1) + ":"))
#generating city names
citynames=list(range(mat.shape[0]))#rowsXcolumns,shape[0]=rows
#removing the starting city
citynames.remove(startcity) #startcity is scanned, so, we need to generate permutat
#generating permutations
per=list(permutations(citynames))
#print(per)
st=time.process_time()
besttourlength=np.inf
for tour in per:
  tourlength=0
  for i in range(len(tour)-1):
    tourlength+=mat[tour[i],tour[i+1]]
    tourlength+=mat[tour[i+1],startcity] #lastcity to startcity
    tourlength+=mat[startcity,tour[0]] #startcity to actual second city
    if tourlength < besttourlength: #minimum logic
      besttourlength=tourlength
      besttour=tour
      besttour=list(besttour)
      besttour.insert(0,startcity) #inserting startcity
et=time.process_time()
time_taken_ms=(et-st)*1000
print("Best Tour:", besttour)
print("Best Tour's Length:", besttourlength)
print("Time Taken:",time_taken_ms)

[[  0 633 257  91 412 150  80 134 259 505 353]
 [633   0 390 661 227 488 572 530 555 289 282]
 [257 390   0 228 169 112 196 154 372 262 110]
 [ 91 661 228   0 383 120  77 105 175 476 324]
 [412 227 169 383   0 267 351 309 338 196  61]
 [150 488 112 120 267   0  63  34 264 360 208]
 [ 80 572 196  77 351  63   0  29 232 444 292]
 [134 530 154 105 309  34  29   0 249 402 250]
 [259 555 372 175 338 264 232 249   0 495 352]
 [505 289 262 476 196 360 444 402 495   0 154]
 [353 282 110 324  61 208 292 250 352 154   0]]
Enter the start city from 0 to 10:1
Best Tour: [1, 4, 10, 0, 2, 3, 5, 6, 7, 8, 9]
Best Tour's Length: 570
Time Taken: 47857.554320999996


In [ ]:
#TSP using Nearest Neighbour Heuristic, not always optimal
#Read the data
import pandas as pd
import time
mat=pd.read_csv("/content/11citytsp.csv", header=None).values.astype(float)
#asking for the starting city
startcity=int(input("Enter the start city from 0 to " + str(mat.shape[0]-1) + ":"))
st=time.process_time()
tourlength=0
besttour=[startcity] #startcity is already scanned
mat[mat==0]=np.inf #cities x-x are marked as Inf
print(mat)
matorigcopy=mat.copy() #at the end, we will be required to come back to startcity
for i in range(mat.shape[0]-1):
    if i==0:
      tourlength+=min(mat[startcity,:])
      nextbestind=np.argmin(mat[startcity,:])
      besttour.append(nextbestind)
      mat[:,nextbestind]=np.inf #can't visit again
      mat[:,startcity]=np.inf #can't visit again except at the end, we will be re
    else:
      tourlength+=min(mat[nextbestind,:])
      nextbestind=np.argmin(mat[nextbestind,:])
      mat[:,nextbestind]=np.inf #can't visit again
      besttour.append(nextbestind)

tourlength+=matorigcopy[nextbestind,startcity] #lastcity to startcity
et=time.process_time()
time_taken_ms=(et-st)*1000
print("Best Tour:", besttour)
print("Best Tour's Length:", tourlength)
print("Time Taken:",time_taken_ms)


In [7]:
import numpy as np

array = np.array([10, 5, 8, 4, 9])
min_index = np.argmin(array)
print("Index of the minimum value:", min_index)

Index of the minimum value: 3


In [ ]:
#write a python code for travelling salesman problem using brute force for 4 cities
# p,q,r,s, lengths are p to q=3,q to s=4,p to r=6,r to s=2,p to s=8,r to q =9
#without using brute force function

import itertools

# Function to calculate the total distance for a given path
def tour_distance(path, distances):
    total = 0
    for i in range(len(path) - 1):
        total += distances[path[i]][path[i + 1]]
    total += distances[path[-1]][path[0]]
     # Add the distance from the last city back to the starting city
    return total

# Define the cities and their distances
cities = ['p', 'q', 'r', 's']
distances = {
    'p': {'p': 0, 'q': 3, 'r': 6, 's': 8},
    'q': {'p': 3, 'q': 0, 'r': 9, 's': 4},
    'r': {'p': 6, 'q': 9, 'r': 0, 's': 2},
    's': {'p': 8, 'q': 4, 'r': 2, 's': 0}
}

# Initialize variables to store the shortest path and distance
shortest_distance = float('inf')
shortest_path = None

# Iterate through all possible permutations of cities
for perm in itertools.permutations(cities):
    # Calculate the total distance for the current permutation
    dist = tour_distance(perm, distances)
    # Update the shortest distance and path if the current permutation has a shorter distance
    if dist < shortest_distance:
        shortest_distance = dist
        shortest_path = perm

# Print the result
print("Shortest Path:", shortest_path)
print("Shortest Distance:", shortest_distance)


Shortest Path: ('p', 'q', 's', 'r')
Shortest Distance: 15


In [ ]:
import itertools

# Function to calculate the total distance for a given path
def total_distance(path, distances):
    total = 0
    for i in range(len(path) - 1):
        total += distances[path[i]][path[i + 1]]
    total += distances[path[-1]][path[0]]
     # Add the distance from the last city back to the starting city
    return total

# Function to find the shortest path using brute force
def brute_force_tsp(cities, distances):
    shortest_path = None
    shortest_distance = float('inf')
    for perm in itertools.permutations(cities):
        dist = total_distance(perm, distances)
        if dist < shortest_distance:
            shortest_distance = dist
            shortest_path = perm
    return shortest_path, shortest_distance

# Define the cities and their distances
cities = ['p', 'q', 'r', 's']
distances = {
    'p': {'p': 0, 'q': 3, 'r': 6, 's': 8},
    'q': {'p': 3, 'q': 0, 'r': 9, 's': 4},
    'r': {'p': 6, 'q': 9, 'r': 0, 's': 2},
    's': {'p': 8, 'q': 4, 'r': 2, 's': 0}
}

# Solve the TSP using brute force
shortest_path, shortest_distance = brute_force_tsp(cities, distances)

# Print the result
print("Shortest Path:", shortest_path)
print("Shortest Distance:", shortest_distance)
